### ISSUE TITLE
wfm

### ISSUE THREAD

**Issue by peepo** [tomverbeure/upduino#1]
tom,

wanted to thank you, as I had tried various....

on warmth: my board looks as though ftdi may be shorting due to excess solder/jumps

did not find email contact

best

**Comment by Idorobots** [comment]
My boards are getting pretty warm as well, though in my case it's the 1.2V regulator area instead of the FTDI chip. Perhaps the FPGAs shipped on these boards have subpar thermals? Hence the low price.

Would love it if anyone found a way to decrease the temperature of the board as it quickly gets uncomfortable to hold.

**Comment by tomverbeure** [comment]
I bought a few other boards and they didn't have this issue. So there's a good chance that it's indeed a QA soldering issue.

Tom
